
export default {
    "header.title": "AEON",
    "header.settingsButton": "Settings",
    "header.feedbackButton": "Send Feedback",
    "header.analyzeAllButton": "Analyze All",
    "header.analyzeSelectedButton": "Analyze Selected",
    "header.analyzingButton": "Analyzing...",
    "header.analyzeButtonDisabledTooltip": "Please select an active API key in settings to enable analysis.",
    "header.analyzeButton.noKeyWarning": "No active API key selected.",

    "app.tab.scores": "Scores",
    "app.tab.pairs": "Currency Pairs",
    "app.tab.charts": "Charts",
    "app.tab.risk": "Risk Sentiment",
    "app.tab.recap": "Recap",
    "app.tab.events": "Events",
    "app.tab.journal": "Journal",
    "app.tab.scrapinglog": "Scraping Log",

    "pairs.table.header.pair": "Pair",
    "pairs.table.header.bias": "Trading Bias",
    "pairs.table.header.deviationSpread": "Deviation Spread",

    "table.header.currency": "Currency",
    "table.header.direction": "Direction",
    "table.header.score": "Score",
    "table.header.basescore": "Base Score",
    "table.header.modifiedscore": "Modified Score",
    "table.header.riskmodifier": "Risk Modifier",
    "table.tooltip.scoreDetails": "Click to see details for {currencyCode} - {indicator}",

    "indicator.group.sentiment": "Sentiment",
    "indicator.group.inflation": "Inflation",
    "indicator.group.growth": "Growth",
    "indicator.group.labourmarket": "Labour Market",
    "indicator.group.monetary": "Monetary",
    "indicator.group.market": "Market",

    "indicator.manufacturingpmi": "Manufacturing PMI",
    "indicator.servicespmi": "Services PMI",
    "indicator.consumerconfidence": "Consumer Confidence",
    "indicator.businessconfidence": "Business Confidence",
    "indicator.cpi": "CPI",
    "indicator.coreppiyoy": "Core PPI YoY",
    "indicator.averagehourlyearningsyoy": "Average Hourly Earnings YoY",
    "indicator.averagemonthlyearnings": "Average Monthly Earnings",
    "indicator.averageweeklywages": "Average Weekly Wages",
    "indicator.averageweeklyearnings": "Average Weekly Earnings",
    "indicator.averagemonthlywages": "Average Monthly Wages",
    "indicator.grossmonthlywage": "Gross Monthly Wage",
    "indicator.unemploymentrate": "Unemployment Rate",
    "indicator.employmentchange": "Employment Change",
    "indicator.jobvacancies": "Job Vacancies",
    "indicator.jobvacancyrate": "Job Vacancy Rate",
    "indicator.employmentchange/nfp": "Employment Change / NFP",
    "indicator.adpemploymentchange": "ADP Employment Change",
    "indicator.unemploymentclaims": "Unemployment Claims",
    "indicator.joltsjobopenings": "JOLTS Job Openings",
    "indicator.claimantcount": "Claimant Count",
    "indicator.gdpq/qannualized": "GDP Q/Q Annualized",
    "indicator.retailsalesm/m": "Retail Sales M/M",
    "indicator.moneysupply": "Money Supply",
    "indicator.centralbank": "Central Bank",
    "indicator.seasonality": "Seasonality",
    "indicator.cot": "COT",
    "indicator.retailsentiment": "Retail Sentiment",
    "indicator.strongvsweak": "Strong vs Weak",
    "indicator.eventmodifiers": "Event Modifiers",
    "indicator.eventmodifier": "Event Modifier",
    
    "charts.title": "Historical Charts",
    "charts.description": "Visualize analysis data over time. A new data snapshot is saved once per day when analysis is run.",
    "charts.selectCurrency": "Select Currency",
    "charts.selectMetrics": "Select Metrics to Display",
    "charts.metric.sigmaScore": "Sigma Score",
    "charts.metric.deviation": "Deviation from Median",
    "charts.metric.median": "Median Score",
    "charts.noData": "No historical data available. Run an analysis to save the first snapshot.",
    "charts.generalMetrics": "General Metrics",
    "charts.indicators": "Indicators",

    "settings.title": "Settings",
    "settings.closeAriaLabel": "Close settings",
    "settings.button.save": "Save Changes",
    "settings.button.cancel": "Cancel",
    "settings.button.close": "Close",

    "settings.tab.sources": "Data Sources",
    "settings.tab.apiKeys": "API Keys",
    "settings.tab.aiSettings": "AI Settings",
    "settings.tab.appearance": "Appearance",
    "settings.tab.localization": "Localization",
    "settings.tab.data": "Data Management",

    "settings.sources.title": "Indicator Source URLs",
    "settings.sources.description": "Provide the URLs for the AI to analyze for each economic indicator. Select a currency to configure its specific sources.",
    "settings.sources.removeUrlAriaLabel": "Remove URL",
    "settings.sources.addUrl": "Add URL",
    "settings.sources.urlPlaceholder": "https://...",

    "settings.apiKeys.manage.title": "Manage API Keys",
    "settings.apiKeys.manage.description": "Add your API keys from different providers. The selected key will be used for all AI analysis.",
    "settings.apiKeys.manage.noKeys": "No API keys added yet.",
    "settings.apiKeys.manage.removeAriaLabel": "Remove API key",
    "settings.apiKeys.add.title": "Add New AI API Key",
    "settings.apiKeys.add.provider": "Provider",
    "settings.apiKeys.add.namePlaceholder": "Key Nickname",
    "settings.apiKeys.add.keyPlaceholder": "API Key",
    "settings.apiKeys.add.addButton": "Add Key",
    "settings.apiKeys.add.addError": "Please fill in all fields to add a new API key.",

    "settings.ai.model.title": "AI Model Selection",
    "settings.ai.model.description": "Choose the AI model to use for each provider. The model corresponding to your active API key's provider will be used.",
    "settings.ai.model.gemini": "Gemini",
    "settings.ai.model.openai": "OpenAI",
    "settings.ai.model.deepseek": "DeepSeek",
    "settings.ai.model.openrouter": "OpenRouter",
    "settings.ai.model.openrouter.free": "Free",
    "settings.ai.model.openrouter.paid": "Paid",
    "settings.ai.recapStyle.title": "Economic Recap Style",
    "settings.ai.recapStyle.description": "Select the style for the AI-generated economic recaps.",
    "settings.ai.recapStyle.label": "Recap Style",
    "settings.ai.recapStyle.option.default": "Default (Professional)",
    "settings.ai.recapStyle.option.default.description": "Provides a concise, data-driven narrative suitable for professional traders and analysts.",
    "settings.ai.recapStyle.option.simplified": "Simplified",
    "settings.ai.recapStyle.option.simplified.description": "Uses simpler language, suitable for learners, without sacrificing key data points.",
    "settings.ai.retry.title": "Automatic Retries on Failure",
    "settings.ai.retry.description": "If an AI analysis fails, the app can automatically retry. Configure the number of attempts for each action.",
    "settings.ai.retry.analyzeAll.title": "Indicator Analysis (Analyze All)",
    "settings.ai.retry.generateRecap.title": "Economic Recap Generation",
    "settings.ai.retry.enable": "Enable Retries",
    "settings.ai.retry.attempts": "Attempts",
    "settings.ai.scoreModification.title": "Automatic Score Modifications",
    "settings.ai.scoreModification.autoApplyEvent": "Auto-apply Event Modifier",
    "settings.ai.scoreModification.descriptionEvent": "When enabled, the AI's recommended score modifier from the economic recap will be automatically applied to the Event Modifier column.",
    "settings.ai.scoreModification.autoApplyRisk": "Auto-apply Risk Modifier",
    "settings.ai.scoreModification.descriptionRisk": "When enabled, the modifier from the Risk Sentiment Dashboard will be automatically applied to the Risk Modifier column based on market conditions.",

    "settings.appearance.theme.title": "Theme",
    "settings.appearance.theme.description": "Choose how AEON looks. Your preference will be saved for your next visit.",
    "settings.localization.language.title": "Language Settings",
    "settings.localization.language.description": "Choose the display language for the AEON application interface.",
    "settings.localization.language.selectLabel": "Select Language",

    "settings.data.backup.title": "Backup & Restore",
    "settings.data.backup.description": "Save a complete snapshot of all your settings, analysis data, historical charts, and trade journal to a single file. This can be used for backup or to transfer your workspace to another device.",
    "settings.data.backup.exportButton": "Export All Data",
    "settings.data.backup.importButton": "Import from Backup",
    "settings.data.import.success": "Complete application state imported successfully!",
    "settings.data.import.error": "Error importing file",
    "settings.data.import.error.format": "Invalid backup file format.",

    "analysisModal.title.currencyAnalysis": "Analysis for",
    "analysisModal.title.indicatorAnalysis": "Analysis for",
    "analysisModal.indicator.noRationale": "No analysis has been performed for this indicator yet.",
    "analysisModal.indicator.rawData": "Raw Data from AI",
    "analysisModal.indicator.manualOverride": "Manual Score Override",
    "analysisModal.indicator.selectScore": "Select a score",
    "analysisModal.indicator.sources": "Configured Sources",
    "analysisModal.indicator.scoringRules": "Scoring Rules",
    "analysisModal.indicator.rationalePlaceholder": "Enter rationale for the score...",
    "analysisModal.indicator.saveButton": "Save Changes",

    "analysisModal.recap.title": "Economic Recap",
    "analysisModal.recap.button.regenerate": "Regenerate",
    "analysisModal.recap.button.loading": "Generating...",
    "analysisModal.recap.button.generate": "Generate Recap",
    "analysis.recap.generating.attempt": "Attempt {current}/{max}",
    "analysisModal.recap.apiKeyWarning": "An active API key is required to generate a recap.",
    "analysisModal.recap.error.generic": "An unknown error occurred while generating the recap.",
    "analysisModal.recap.notGenerated": "Recap Not Yet Generated",

    "analysisModal.eventModifier.title": "Event Modifier Details",
    "analysisModal.eventModifier.currentValue": "Current Modifier Value",
    "analysisModal.eventModifier.noRecap": "Generate an economic recap on the Recap tab to see the AI's recommendation and event analysis.",

    "centralBank.title": "Central Bank Document Analyzer for {currencyCode}",
    "centralBank.description": "Upload or link to recent central bank documents (e.g., meeting minutes, press conference transcripts) for an AI-powered sentiment analysis.",
    "centralBank.urlPlaceholder": "Enter URL to a document...",
    "centralBank.addUrlButton": "Add URL",
    "centralBank.uploadButton": "Upload Files (.pdf, .txt)",
    "centralBank.sourcesTitle": "Sources for Analysis",
    "centralBank.analyzeButton": "Analyze Sources",
    "centralBank.analyzingButton": "Analyzing...",
    "centralBank.resultTitle": "Analysis Result",
    "centralBank.evidenceTitle": "Supporting Evidence (from document)",
    "centralBank.error": "Failed to analyze the central bank documents. The AI may have returned an invalid response or the content could not be fetched.",

    "journal.title": "Trade Journal",
    "journal.addTrade": "Add New Trade",
    "journal.noTrades": "You have not logged any trades yet. Click 'Add New Trade' to get started.",
    "journal.table.date": "Date",
    "journal.table.pair": "Pair",
    "journal.table.direction": "Direction",
    "journal.table.status": "Status",
    "journal.table.entry": "Entry",
    "journal.table.exit": "Exit",
    "journal.table.size": "Size",
    "journal.table.pnl": "P/L",
    "journal.table.notes": "Notes",
    "journal.table.actions": "Actions",

    "journal.form.title.new": "Log a New Trade",
    "journal.form.title.edit": "Edit Trade",
    "journal.form.entryDate": "Entry Date",
    "journal.form.pair": "Currency Pair",
    "journal.form.direction": "Direction",
    "journal.form.direction.long": "Long",
    "journal.form.direction.short": "Short",
    "journal.form.entryPrice": "Entry Price",
    "journal.form.stopLoss": "Stop Loss",
    "journal.form.takeProfit": "Take Profit",
    "journal.form.status": "Status",
    "journal.form.status.open": "Open",
    "journal.form.status.closed": "Closed",
    "journal.form.exitPrice": "Exit Price",
    "journal.form.pnl": "Profit / Loss (P/L)",
    "journal.form.positionSize": "Position Size (Lots)",
    "journal.form.notes": "Notes / Rationale",
    "journal.form.button.cancel": "Cancel",
    "journal.form.button.save": "Save Trade",

    "risk.title": "Risk Sentiment Dashboard",
    "risk.description": "A rule-based dashboard to gauge the overall market sentiment, acting as a macro filter for currency analysis.",
    "risk.conviction": "Overall Conviction",
    "risk.summary": "{on} On / {neutral} Neutral / {off} Off",
    "risk.loading": "Loading Market Data...",
    "risk.error": "Could not load market data. Please ensure your Market Data API key is configured correctly in settings and is valid.",
    "risk.noApiKey": "Please configure a Market Data API key in Settings to use the Risk Sentiment Dashboard.",
    "risk.refreshButton": "Refresh Analysis",
    "risk.refreshingButton": "Refreshing...",
    "risk.prompt.title": "Risk Sentiment Data Not Loaded",
    "risk.prompt.description": "Click the 'Refresh Analysis' button to fetch and analyze the latest market data.",
    "risk.indicator.spx": "S&P 500 Index",
    "risk.indicator.vix": "VIX Index",
    "risk.indicator.audjpy": "AUD/JPY",
    "risk.indicator.us10y": "US 10-Year Yield",
    "risk.role.spx": "The Market Trend",
    "risk.role.vix": "The Fear Gauge",
    "risk.role.audjpy": "The Risk Barometer",
    "risk.role.us10y": "The Economic Outlook",
    "risk.overrideSignal": "Override Signal",
    "risk.overrideConviction": "Override Conviction",
    "risk.autoSignal": "Auto — {signal}",

    "recap.editButton": "Edit",
    "recap.saveButton": "Save Recap",
    "recap.cancelButton": "Cancel",
    "recap.addEventButton": "Add Event Modifier",
    "recap.editingTitle": "Editing Recap for {currencyCode}",

    "welcome.title": "Welcome to AEON",
    "welcome.intro": "AEON is a powerful tool for economic analysis. Before you begin, you'll need to set up API keys. Would you like a quick tour of the app's features?",
    "welcome.aiApi.title": "AI Analysis API Key",
    "welcome.aiApi.description": "For scoring indicators and generating economic recaps, AEON needs an AI API key (e.g., Gemini). You can add your own key in the settings.",
    "welcome.marketApi.title": "Market Data API Key",
    "welcome.marketApi.description": "To use the Risk Sentiment Dashboard, an API key from Alpha Vantage is required. You can get a free key, which has daily usage limits, or purchase a premium key for higher limits. This allows AEON to fetch the latest stock, FX, and yield data for analysis.",
    "welcome.alphaVantageLink": "Get your Alpha Vantage key here.",
    "welcome.getApiKeyTitle": "How to get an API Key",
    "welcome.instructions.gemini.title": "How to get a Gemini API Key",
    "welcome.instructions.gemini.step1": "Go to Google AI Studio.",
    "welcome.instructions.gemini.step2": "Log in with your Google account.",
    "welcome.instructions.gemini.step3": "Click on 'Get API key' in the top left menu.",
    "welcome.instructions.gemini.step4": "Create a new API key in a new or existing project.",
    "welcome.instructions.gemini.step5": "Copy the key and paste it into the AEON settings.",
    "welcome.instructions.openai.title": "How to get an OpenAI API Key",
    "welcome.instructions.openai.step1": "Go to the OpenAI Platform website.",
    "welcome.instructions.openai.step2": "Log in or create a new account.",
    "welcome.instructions.openai.step3": "Navigate to the 'API Keys' section in your account settings.",
    "welcome.instructions.openai.step4": "Create a new secret key.",
    "welcome.instructions.openai.step5": "Copy the key and paste it into the AEON settings. Note: you may need to set up a payment method.",
    "welcome.instructions.deepseek.title": "How to get a DeepSeek API Key",
    "welcome.instructions.deepseek.step1": "Go to the DeepSeek platform website.",
    "welcome.instructions.deepseek.step2": "Log in or create a new account.",
    "welcome.instructions.deepseek.step3": "Navigate to the 'API Keys' section.",
    "welcome.instructions.deepseek.step4": "Create a new API key.",
    "welcome.instructions.deepseek.step5": "Copy the key and paste it into the AEON settings.",
    "welcome.instructions.openrouter.title": "How to get an OpenRouter API Key",
    "welcome.instructions.openrouter.step1": "Go to the OpenRouter.ai website.",
    "welcome.instructions.openrouter.step2": "Log in with a Google, GitHub, or email account.",
    "welcome.instructions.openrouter.step3": "Navigate to the 'Keys' page from your account menu.",
    "welcome.instructions.openrouter.step4": "Create a new key.",
    "welcome.instructions.openrouter.step5": "Copy the key and paste it into the AEON settings. You may need to add credits for paid models.",
    "welcome.button.startTour": "Start Tour",
    "welcome.button.skipTour": "Skip Tour",

    "tour.button.next": "Got It!",
    "tour.button.end": "End Tour",

    "tour.scores.title": "The Scores Dashboard",
    "tour.scores.content": "This is the main hub of AEON. Here's a quick rundown:\n\n**Running Analysis:** Use the 'Analyze All' button in the top right. You can toggle 'Fetch Data Only' to just update the raw data without using AI credits. Hold 'Shift' while clicking 'Analyze' to force a re-analysis, ignoring any cached data.\n\n**Making Selections:** You can analyze specific items by selecting them first. **'Shift-click'** a currency name to select its row, an indicator header to select its column, or an individual score cell to select it. This unified control makes it easy to build a targeted analysis.\n\n**Viewing Details:** Click on any currency name, indicator header, or score cell to open a detailed view with AI rationale, scoring rules, and manual override options.",

    "tour.risk.title": "Risk Sentiment Dashboard",
    "tour.risk.content": "This dashboard provides a high-level view of market sentiment. It analyzes key indicators like the S&P 500, VIX, AUD/JPY, and US Treasury yields to determine if the market is in a 'Risk-On' or 'Risk-Off' mood. This serves as a macro filter to complement your individual currency analysis.",

    "tour.pairs.title": "Currency Pairs View",
    "tour.pairs.content": "This screen automatically calculates and ranks all possible currency pairs based on the deviation of their scores from the median. A large positive 'Deviation Spread' suggests a bullish bias for the pair (buy the first currency, sell the second), while a large negative spread suggests a bearish bias.",

    "tour.recap.title": "Economic Recap",
    "tour.recap.content": "Here, the AI generates a detailed narrative summary for the selected currency based on its scored indicators. It identifies the overall bias (e.g., Hawkish, Dovish) and highlights significant recent events that could impact the currency's value, even recommending a score modifier.",

    "tour.events.title": "Events Analysis",
    "tour.events.content": "This page displays the specific 'Notable Event Modifiers' that the AI identified while generating the Economic Recap. It provides a focused look at the key news and data releases influencing a currency.",

    "tour.charts.title": "Historical Charts",
    "tour.charts.content": "This section visualizes how currency scores have changed over time. Each time you run an analysis, a snapshot of the day's scores is saved, allowing you to track trends in the data and a currency's fundamental strength.",

    "tour.journal.title": "Trade Journal",
    "tour.journal.content": "A simple and effective tool to log your trades. Keeping a journal helps you track your performance, analyze your decisions, and maintain discipline in your trading strategy.",

    "tour.log.title": "Scraping Log",
    "tour.log.content": "This is a technical log for troubleshooting. It shows the detailed output from the last data fetching and analysis run, including which URLs were accessed and whether the process was successful. It's useful for debugging if an indicator fails to get a score.",

    "feedback.title": "Send Feedback",
    "feedback.type.label": "Feedback Type",
    "feedback.type.bug": "Bug Report",
    "feedback.type.feature": "Feature Request",
    "feedback.type.general": "General Feedback",
    "feedback.subject.label": "Subject",
    "feedback.subject.placeholder": "e.g., App crashes when switching tabs",
    "feedback.description.label": "Description",
    "feedback.description.placeholder": "Please provide as much detail as possible. If reporting a bug, include the steps to reproduce it.",
    "feedback.email.label": "Your Email (Optional)",
    "feedback.email.placeholder": "Enter your email for follow-up questions",
    "feedback.attachInfo.label": "Attach System & App Info",
    "feedback.attachInfo.description": "Includes browser info and a snapshot of current app data to help us debug issues faster.",
    "feedback.button.submit": "Submit via Email",
    "feedback.alert.submitted": "Your default email client will now open. Please review and send the email. Thank you for your feedback!",

    "rationale.modal.title": "Rationale for {currency} Event Modifier",
    "rationale.modal.label": "Provide your reasoning for this manual override:",
    "rationale.modal.saveButton": "Save Rationale",
    "rationale.modal.tooltip": "Edit Rationale"
}