
export default {
    "header.title": "AEON",
    "header.settingsButton": "Instellingen",
    "header.feedbackButton": "Feedback Sturen",
    "header.analyzeAllButton": "Analyseer Alles",
    "header.analyzeSelectedButton": "Analyseer Selectie",
    "header.analyzingButton": "Analyseren...",
    "header.analyzeButtonDisabledTooltip": "Selecteer een actieve API-sleutel in de instellingen om analyse in te schakelen.",
    "header.analyzeButton.noKeyWarning": "Geen actieve API-sleutel geselecteerd.",

    "app.tab.scores": "Scores",
    "app.tab.pairs": "Valutaparen",
    "app.tab.charts": "Grafieken",
    "app.tab.risk": "Risicosentiment",
    "app.tab.recap": "Samenvatting",
    "app.tab.events": "Gebeurtenissen",
    "app.tab.journal": "Dagboek",
    "app.tab.scrapinglog": "Scraping Log",

    "pairs.table.header.pair": "Paar",
    "pairs.table.header.bias": "Handelsbias",
    "pairs.table.header.deviationSpread": "Deviatie Spread",

    "table.header.currency": "Valuta",
    "table.header.direction": "Richting",
    "table.header.score": "Score",
    "table.header.basescore": "Basisscore",
    "table.header.modifiedscore": "Aangepaste Score",
    "table.header.riskmodifier": "Risico Modifier",
    "table.tooltip.scoreDetails": "Klik om details te zien voor {currencyCode} - {indicator}",

    "indicator.group.sentiment": "Sentiment",
    "indicator.group.inflation": "Inflatie",
    "indicator.group.growth": "Groei",
    "indicator.group.labourmarket": "Arbeidsmarkt",
    "indicator.group.monetary": "Monetair",
    "indicator.group.market": "Markt",

    "indicator.manufacturingpmi": "Productie PMI",
    "indicator.servicespmi": "Diensten PMI",
    "indicator.consumerconfidence": "Consumentenvertrouwen",
    "indicator.businessconfidence": "Ondernemersvertrouwen",
    "indicator.cpi": "CPI",
    "indicator.coreppiyoy": "Kern PPI YoY",
    "indicator.averagehourlyearningsyoy": "Gem. Uurloon YoY",
    "indicator.averagemonthlyearnings": "Gem. Maandinkomen",
    "indicator.averageweeklywages": "Gem. Weekloon",
    "indicator.averageweeklyearnings": "Gem. Weekinkomen",
    "indicator.averagemonthlywages": "Gem. Maandloon",
    "indicator.grossmonthlywage": "Bruto Maandloon",
    "indicator.unemploymentrate": "Werkloosheidspercentage",
    "indicator.employmentchange": "Werkgelegenheidsverandering",
    "indicator.jobvacancies": "Vacatures",
    "indicator.jobvacancyrate": "Vacaturegraad",
    "indicator.employmentchange/nfp": "Werkgelegenheidsverandering / NFP",
    "indicator.adpemploymentchange": "ADP Werkgelegenheidsverandering",
    "indicator.unemploymentclaims": "Werkloosheidsaanvragen",
    "indicator.joltsjobopenings": "JOLTS Vacatures",
    "indicator.claimantcount": "Aantal WW-uitkeringen",
    "indicator.gdpq/qannualized": "BBP Q/Q Geannualiseerd",
    "indicator.retailsalesm/m": "Detailhandelsverkopen M/M",
    "indicator.moneysupply": "Geldhoeveelheid",
    "indicator.centralbank": "Centrale Bank",
    "indicator.seasonality": "Seizoensgebondenheid",
    "indicator.cot": "COT",
    "indicator.retailsentiment": "Retail Sentiment",
    "indicator.strongvsweak": "Sterk vs Zwak",
    "indicator.eventmodifiers": "Gebeurtenismodificatoren",
    "indicator.eventmodifier": "Gebeurtenismodificator",
    
    "charts.title": "Historische Grafieken",
    "charts.description": "Visualiseer analysegegevens in de tijd. Er wordt één keer per dag een nieuwe gegevensmomentopname opgeslagen wanneer de analyse wordt uitgevoerd.",
    "charts.selectCurrency": "Selecteer Valuta",
    "charts.selectMetrics": "Selecteer Statistieken om Weer te Geven",
    "charts.metric.sigmaScore": "Sigma Score",
    "charts.metric.deviation": "Afwijking van Mediaan",
    "charts.metric.median": "Mediaan Score",
    "charts.noData": "Geen historische gegevens beschikbaar. Voer een analyse uit om de eerste momentopname op te slaan.",
    "charts.generalMetrics": "Algemene Statistieken",
    "charts.indicators": "Indicatoren",

    "settings.title": "Instellingen",
    "settings.closeAriaLabel": "Sluit instellingen",
    "settings.button.save": "Wijzigingen Opslaan",
    "settings.button.cancel": "Annuleren",
    "settings.button.close": "Sluiten",

    "settings.tab.sources": "Gegevensbronnen",
    "settings.tab.apiKeys": "API-sleutels",
    "settings.tab.aiSettings": "AI-instellingen",
    "settings.tab.appearance": "Uiterlijk",
    "settings.tab.localization": "Lokalisatie",
    "settings.tab.data": "Gegevensbeheer",

    "settings.sources.title": "Indicator Bron-URL's",
    "settings.sources.description": "Voer de URL's in die de AI moet analyseren voor elke economische indicator. Selecteer een valuta om de specifieke bronnen te configureren.",
    "settings.sources.removeUrlAriaLabel": "Verwijder URL",
    "settings.sources.addUrl": "URL Toevoegen",
    "settings.sources.urlPlaceholder": "https://...",

    "settings.apiKeys.manage.title": "API-sleutels Beheren",
    "settings.apiKeys.manage.description": "Voeg uw API-sleutels van verschillende providers toe. De geselecteerde sleutel wordt gebruikt voor alle AI-analyses.",
    "settings.apiKeys.manage.noKeys": "Nog geen API-sleutels toegevoegd.",
    "settings.apiKeys.manage.removeAriaLabel": "Verwijder API-sleutel",
    "settings.apiKeys.add.title": "Nieuwe AI API-sleutel Toevoegen",
    "settings.apiKeys.add.provider": "Provider",
    "settings.apiKeys.add.namePlaceholder": "Bijnaam voor sleutel",
    "settings.apiKeys.add.keyPlaceholder": "API-sleutel",
    "settings.apiKeys.add.addButton": "Sleutel Toevoegen",
    "settings.apiKeys.add.addError": "Vul alstublieft alle velden in om een nieuwe API-sleutel toe te voegen.",

    "settings.ai.model.title": "AI Model Selectie",
    "settings.ai.model.description": "Kies het AI-model dat voor elke provider moet worden gebruikt. Het model dat overeenkomt met de provider van uw actieve API-sleutel wordt gebruikt.",
    "settings.ai.model.gemini": "Gemini",
    "settings.ai.model.openai": "OpenAI",
    "settings.ai.model.deepseek": "DeepSeek",
    "settings.ai.model.openrouter": "OpenRouter",
    "settings.ai.model.openrouter.free": "Gratis",
    "settings.ai.model.openrouter.paid": "Betaald",
    "settings.ai.recapStyle.title": "Stijl Economische Samenvatting",
    "settings.ai.recapStyle.description": "Selecteer de stijl voor de door AI gegenereerde economische samenvattingen.",
    "settings.ai.recapStyle.label": "Stijl Samenvatting",
    "settings.ai.recapStyle.option.default": "Standaard (Professioneel)",
    "settings.ai.recapStyle.option.default.description": "Biedt een beknopte, datagestuurde samenvatting die geschikt is voor professionele handelaren en analisten.",
    "settings.ai.recapStyle.option.simplified": "Vereenvoudigd",
    "settings.ai.recapStyle.option.simplified.description": "Gebruikt eenvoudigere taal, geschikt voor beginners, zonder belangrijke datapunten op te offeren.",
    "settings.ai.retry.title": "Automatische Pogingen bij Fouten",
    "settings.ai.retry.description": "Als een AI-analyse mislukt, kan de app het automatisch opnieuw proberen. Configureer het aantal pogingen voor elke actie.",
    "settings.ai.retry.analyzeAll.title": "Indicatoranalyse (Analyseer Alles)",
    "settings.ai.retry.generateRecap.title": "Genereren Economische Samenvatting",
    "settings.ai.retry.enable": "Pogingen Inschakelen",
    "settings.ai.retry.attempts": "Pogingen",
    "settings.ai.scoreModification.title": "Automatische Scoremodificaties",
    "settings.ai.scoreModification.autoApplyEvent": "Gebeurtenismodificator Automatisch Toepassen",
    "settings.ai.scoreModification.descriptionEvent": "Indien ingeschakeld, wordt de door de AI aanbevolen scoremodificator uit de economische samenvatting automatisch toegepast op de kolom Gebeurtenismodificator.",
    "settings.ai.scoreModification.autoApplyRisk": "Risicomodificator Automatisch Toepassen",
    "settings.ai.scoreModification.descriptionRisk": "Indien ingeschakeld, wordt de modificator van het Risicosentiment Dashboard automatisch toegepast op de Risicomodificator-kolom op basis van marktomstandigheden.",

    "settings.appearance.theme.title": "Thema",
    "settings.appearance.theme.description": "Kies hoe AEON eruitziet. Uw voorkeur wordt opgeslagen voor uw volgende bezoek.",
    "settings.localization.language.title": "Taalinstellingen",
    "settings.localization.language.description": "Kies de weergavetaal voor de AEON-applicatie-interface.",
    "settings.localization.language.selectLabel": "Selecteer Taal",

    "settings.data.backup.title": "Back-up & Herstel",
    "settings.data.backup.description": "Sla een volledige momentopname op van al uw instellingen, analysegegevens, historische grafieken en handelsdagboek in één bestand. Dit kan worden gebruikt voor back-up of om uw werkruimte over te dragen naar een ander apparaat.",
    "settings.data.backup.exportButton": "Exporteer Alle Gegevens",
    "settings.data.backup.importButton": "Importeer van Back-up",
    "settings.data.import.success": "Volledige applicatiestatus succesvol geïmporteerd!",
    "settings.data.import.error": "Fout bij het importeren van het bestand",
    "settings.data.import.error.format": "Ongeldig back-upbestandsformaat.",

    "analysisModal.title.currencyAnalysis": "Analyse voor",
    "analysisModal.title.indicatorAnalysis": "Analyse voor",
    "analysisModal.indicator.noRationale": "Er is nog geen analyse uitgevoerd voor deze indicator.",
    "analysisModal.indicator.rawData": "Ruwe Data van AI",
    "analysisModal.indicator.manualOverride": "Handmatige Score Aanpassing",
    "analysisModal.indicator.selectScore": "Selecteer een score",
    "analysisModal.indicator.sources": "Geconfigureerde Bronnen",
    "analysisModal.indicator.scoringRules": "Scoreregels",
    "analysisModal.indicator.rationalePlaceholder": "Voer de reden voor de score in...",
    "analysisModal.indicator.saveButton": "Wijzigingen Opslaan",
    "analysisModal.recap.title": "Economische Samenvatting",
    "analysisModal.recap.button.regenerate": "Opnieuw Genereren",
    "analysisModal.recap.button.loading": "Genereren...",
    "analysisModal.recap.button.generate": "Genereer Samenvatting",
    "analysis.recap.generating.attempt": "Poging {current}/{max}",
    "analysisModal.recap.apiKeyWarning": "Een actieve API-sleutel is vereist om een samenvatting te genereren.",
    "analysisModal.recap.error.generic": "Er is een onbekende fout opgetreden bij het genereren van de samenvatting.",
    "analysisModal.recap.notGenerated": "Samenvatting Nog Niet Gegenereerd",
    "analysisModal.eventModifier.title": "Details Gebeurtenismodificator",
    "analysisModal.eventModifier.currentValue": "Huidige Modificatorwaarde",
    "analysisModal.eventModifier.noRecap": "Genereer een economische samenvatting op het tabblad Samenvatting om de aanbeveling en gebeurtenisanalyse van de AI te zien.",

    "centralBank.title": "Centrale Bank Document Analyzer voor {currencyCode}",
    "centralBank.description": "Upload of link naar recente documenten van de centrale bank (bijv. notulen, persconferenties) voor een AI-gestuurde sentimentanalyse.",
    "centralBank.urlPlaceholder": "Voer URL naar een document in...",
    "centralBank.addUrlButton": "URL Toevoegen",
    "centralBank.uploadButton": "Bestanden Uploaden (.pdf, .txt)",
    "centralBank.sourcesTitle": "Bronnen voor Analyse",
    "centralBank.analyzeButton": "Analyseer Bronnen",
    "centralBank.analyzingButton": "Analyseren...",
    "centralBank.resultTitle": "Analyseresultaat",
    "centralBank.evidenceTitle": "Ondersteunend Bewijs (uit document)",
    "centralBank.error": "Analyse van de centrale bank documenten is mislukt. De AI heeft mogelijk een ongeldig antwoord gegeven of de inhoud kon niet worden opgehaald.",
    
    "journal.title": "Handelsdagboek",
    "journal.addTrade": "Nieuwe Trade Toevoegen",
    "journal.noTrades": "U heeft nog geen trades gelogd. Klik op 'Nieuwe Trade Toevoegen' om te beginnen.",
    "journal.table.date": "Datum",
    "journal.table.pair": "Paar",
    "journal.table.direction": "Richting",
    "journal.table.status": "Status",
    "journal.table.entry": "Instap",
    "journal.table.exit": "Uitstap",
    "journal.table.size": "Grootte",
    "journal.table.pnl": "W/V",
    "journal.table.notes": "Notities",
    "journal.table.actions": "Acties",

    "journal.form.title.new": "Log een Nieuwe Trade",
    "journal.form.title.edit": "Trade Bewerken",
    "journal.form.entryDate": "Instapdatum",
    "journal.form.pair": "Valutapaar",
    "journal.form.direction": "Richting",
    "journal.form.direction.long": "Long",
    "journal.form.direction.short": "Short",
    "journal.form.entryPrice": "Instapprijs",
    "journal.form.stopLoss": "Stop Loss",
    "journal.form.takeProfit": "Take Profit",
    "journal.form.status": "Status",
    "journal.form.status.open": "Open",
    "journal.form.status.closed": "Gesloten",
    "journal.form.exitPrice": "Uitstapprijs",
    "journal.form.pnl": "Winst / Verlies (W/V)",
    "journal.form.positionSize": "Positiegrootte (Lots)",
    "journal.form.notes": "Notities / Reden",
    "journal.form.button.cancel": "Annuleren",
    "journal.form.button.save": "Trade Opslaan",
    
    "risk.title": "Risicosentiment Dashboard",
    "risk.description": "Een op regels gebaseerd dashboard om het algehele marktsentiment te peilen, dat fungeert als een macrofilter voor valuta-analyse.",
    "risk.conviction": "Algehele Overtuiging",
    "risk.summary": "{on} On / {neutral} Neutraal / {off} Off",
    "risk.loading": "Marktgegevens Laden...",
    "risk.error": "Kon marktgegevens niet laden. Zorg ervoor dat uw Market Data API-sleutel correct is geconfigureerd in de instellingen en geldig is.",
    "risk.noApiKey": "Configureer alstublieft een Market Data API-sleutel in de Instellingen om het Risicosentiment Dashboard te gebruiken.",
    "risk.refreshButton": "Analyse Vernieuwen",
    "risk.refreshingButton": "Vernieuwen...",
    "risk.prompt.title": "Risicosentimentgegevens Niet Geladen",
    "risk.prompt.description": "Klik op de knop 'Analyse Vernieuwen' om de laatste marktgegevens op te halen en te analyseren.",
    "risk.indicator.spx": "S&P 500 Index",
    "risk.indicator.vix": "VIX Index",
    "risk.indicator.audjpy": "AUD/JPY",
    "risk.indicator.us10y": "VS 10-jaars Rente",
    "risk.role.spx": "De Markttrend",
    "risk.role.vix": "De Angstmeter",
    "risk.role.audjpy": "De Risicobarometer",
    "risk.role.us10y": "De Economische Vooruitzichten",
    "risk.overrideSignal": "Signaal Overschrijven",
    "risk.overrideConviction": "Overtuiging Overschrijven",
    "risk.autoSignal": "Auto — {signal}",

    "recap.editButton": "Bewerken",
    "recap.saveButton": "Samenvatting Opslaan",
    "recap.cancelButton": "Annuleren",
    "recap.addEventButton": "Gebeurtenismodificator Toevoegen",
    "recap.editingTitle": "Samenvatting Bewerken voor {currencyCode}",

    "welcome.title": "Welkom bij AEON",
    "welcome.intro": "AEON is een krachtig hulpmiddel voor economische analyse. Voordat u begint, moet u API-sleutels instellen. Wilt u een snelle rondleiding door de functies van de app?",
    "welcome.aiApi.title": "AI Analyse API-sleutel",
    "welcome.aiApi.description": "Voor het scoren van indicatoren en het genereren van economische samenvattingen heeft AEON een AI API-sleutel (bijv. Gemini) nodig. U kunt uw eigen sleutel toevoegen in de instellingen.",
    "welcome.marketApi.title": "Marktgegevens API-sleutel",
    "welcome.marketApi.description": "Om het Risicosentiment Dashboard te gebruiken, is een API-sleutel van Alpha Vantage vereist. U kunt een gratis sleutel krijgen, die dagelijkse gebruikslimieten heeft, of een premium sleutel kopen voor hogere limieten. Hiermee kan AEON de nieuwste aandelen-, FX- en rendementsgegevens ophalen voor analyse.",
    "welcome.alphaVantageLink": "Haal hier uw Alpha Vantage-sleutel op.",
    "welcome.getApiKeyTitle": "Hoe kom ik aan een API-sleutel?",
    "welcome.instructions.gemini.title": "Hoe kom ik aan een Gemini API-sleutel?",
    "welcome.instructions.gemini.step1": "Ga naar Google AI Studio.",
    "welcome.instructions.gemini.step2": "Log in met uw Google-account.",
    "welcome.instructions.gemini.step3": "Klik op 'Get API key' in het menu linksboven.",
    "welcome.instructions.gemini.step4": "Maak een nieuwe API-sleutel aan in een nieuw of bestaand project.",
    "welcome.instructions.gemini.step5": "Kopieer de sleutel en plak deze in de AEON-instellingen.",
    "welcome.instructions.openai.title": "Hoe kom ik aan een OpenAI API-sleutel?",
    "welcome.instructions.openai.step1": "Ga naar de OpenAI Platform-website.",
    "welcome.instructions.openai.step2": "Log in of maak een nieuw account aan.",
    "welcome.instructions.openai.step3": "Navigeer naar de sectie 'API Keys' in uw accountinstellingen.",
    "welcome.instructions.openai.step4": "Maak een nieuwe geheime sleutel aan.",
    "welcome.instructions.openai.step5": "Kopieer de sleutel en plak deze in de AEON-instellingen. Let op: mogelijk moet u een betaalmethode instellen.",
    "welcome.instructions.deepseek.title": "Hoe kom ik aan een DeepSeek API-sleutel?",
    "welcome.instructions.deepseek.step1": "Ga naar de DeepSeek platformwebsite.",
    "welcome.instructions.deepseek.step2": "Log in of maak een nieuw account aan.",
    "welcome.instructions.deepseek.step3": "Navigeer naar de sectie 'API Keys'.",
    "welcome.instructions.deepseek.step4": "Maak een nieuwe API-sleutel aan.",
    "welcome.instructions.deepseek.step5": "Kopieer de sleutel en plak deze in de AEON-instellingen.",
    "welcome.instructions.openrouter.title": "Hoe kom ik aan een OpenRouter API-sleutel?",
    "welcome.instructions.openrouter.step1": "Ga naar de OpenRouter.ai-website.",
    "welcome.instructions.openrouter.step2": "Log in met een Google-, GitHub- of e-mailaccount.",
    "welcome.instructions.openrouter.step3": "Navigeer naar de 'Keys'-pagina vanuit uw accountmenu.",
    "welcome.instructions.openrouter.step4": "Maak een nieuwe sleutel aan.",
    "welcome.instructions.openrouter.step5": "Kopieer de sleutel en plak deze in de AEON-instellingen. Mogelijk moet u tegoed toevoegen voor betaalde modellen.",
    "welcome.button.startTour": "Start Rondleiding",
    "welcome.button.skipTour": "Sla Rondleiding Over",

    "tour.button.next": "Begrepen!",
    "tour.button.end": "Beëindig Rondleiding",

    "tour.scores.title": "Het Scores Dashboard",
    "tour.scores.content": "Dit is de centrale hub van AEON. Hier is een korte uitleg:\n\n**Analyse Uitvoeren:** Gebruik de 'Analyseer Alles'-knop rechtsboven. U kunt 'Alleen Gegevens Ophalen' inschakelen om alleen de ruwe data bij te werken zonder AI-credits te gebruiken. Houd 'Shift' ingedrukt terwijl u op 'Analyseer' klikt om een heranalyse te forceren, waarbij eventuele cachegegevens worden genegeerd.\n\n**Selecties Maken:** U kunt specifieke items analyseren door ze eerst te selecteren. **'Shift-klik'** op een valutanaam om de rij te selecteren, een indicatorheader om de kolom te selecteren, of een individuele scorecel om deze te selecteren. Deze uniforme bediening maakt het eenvoudig om een gerichte analyse samen te stellen.\n\n**Details Bekijken:** Klik op een valutanaam, indicatorheader of scorecel om een gedetailleerde weergave te openen met AI-redenering, scoreregels en handmatige aanpassingsopties.",

    "tour.risk.title": "Risicosentiment Dashboard",
    "tour.risk.content": "Dit dashboard geeft een overzicht van het marktsentiment op hoog niveau. Het analyseert belangrijke indicatoren zoals de S&P 500, VIX, AUD/JPY en Amerikaanse staatsobligaties om te bepalen of de markt in een 'Risk-On'- of 'Risk-Off'-stemming is. Dit dient als een macrofilter om uw individuele valuta-analyse aan te vullen.",

    "tour.pairs.title": "Valutaparen Weergave",
    "tour.pairs.content": "Dit scherm berekent en rangschikt automatisch alle mogelijke valutaparen op basis van de afwijking van hun scores van de mediaan. Een grote positieve 'Deviatie Spread' duidt op een bullish bias voor het paar (koop de eerste valuta, verkoop de tweede), terwijl een grote negatieve spread duidt op een bearish bias.",

    "tour.recap.title": "Economische Samenvatting",
    "tour.recap.content": "Hier genereert de AI een gedetailleerde, verhalende samenvatting voor de geselecteerde valuta op basis van de gescoorde indicatoren. Het identificeert de algehele bias (bijv. Hawkish, Dovish) en belicht belangrijke recente gebeurtenissen die de waarde van de valuta kunnen beïnvloeden, en doet zelfs een aanbeveling voor een scoremodificator.",

    "tour.events.title": "Gebeurtenissenanalyse",
    "tour.events.content": "Deze pagina toont de specifieke 'Opmerkelijke Gebeurtenismodificatoren' die de AI heeft geïdentificeerd bij het genereren van de Economische Samenvatting. Het biedt een gerichte blik op het belangrijkste nieuws en de datareleases die een valuta beïnvloeden.",

    "tour.charts.title": "Historische Grafieken",
    "tour.charts.content": "Dit gedeelte visualiseert hoe de scores van valuta's in de loop van de tijd zijn veranderd. Elke keer dat u een analyse uitvoert, wordt een momentopname van de scores van die dag opgeslagen, zodat u trends in de gegevens en de fundamentele kracht van een valuta kunt volgen.",

    "tour.journal.title": "Handelsdagboek",
    "tour.journal.content": "Een eenvoudig en effectief hulpmiddel om uw transacties te loggen. Het bijhouden van een dagboek helpt u uw prestaties te volgen, uw beslissingen te analyseren en discipline in uw handelsstrategie te behouden.",

    "tour.log.title": "Scraping Log",
    "tour.log.content": "Dit is een technisch logboek voor het oplossen van problemen. Het toont de gedetailleerde uitvoer van de laatste data-ophalings- en analyse-run, inclusief welke URL's zijn benaderd en of het proces succesvol was. Het is handig voor het debuggen als een indicator geen score krijgt.",
    
    "feedback.title": "Feedback Sturen",
    "feedback.type.label": "Soort Feedback",
    "feedback.type.bug": "Bugrapport",
    "feedback.type.feature": "Functieverzoek",
    "feedback.type.general": "Algemene Feedback",
    "feedback.subject.label": "Onderwerp",
    "feedback.subject.placeholder": "bijv., App crasht bij wisselen van tabbladen",
    "feedback.description.label": "Beschrijving",
    "feedback.description.placeholder": "Geef alstublieft zoveel mogelijk details. Als u een bug meldt, vermeld dan de stappen om deze te reproduceren.",
    "feedback.email.label": "Uw E-mail (Optioneel)",
    "feedback.email.placeholder": "Voer uw e-mailadres in voor eventuele vervolgvragen",
    "feedback.attachInfo.label": "Systeem- & App-info Bijvoegen",
    "feedback.attachInfo.description": "Bevat browserinfo en een momentopname van de huidige app-gegevens om ons te helpen problemen sneller op te lossen.",
    "feedback.button.submit": "Verstuur via E-mail",
    "feedback.alert.submitted": "Uw standaard e-mailprogramma wordt nu geopend. Controleer en verzend de e-mail. Bedankt voor uw feedback!",

    "rationale.modal.title": "Reden voor {currency} Gebeurtenismodificator",
    "rationale.modal.label": "Geef uw reden voor deze handmatige aanpassing:",
    "rationale.modal.saveButton": "Reden Opslaan",
    "rationale.modal.tooltip": "Reden Bewerken"
}